services:
  app:
    build: .
    container_name: anime_tracker_app
    expose:
      - 3000
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: mysql
    container_name: anime_tracker_database
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${DATABASE}
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - .:/app
      - /app/node_modules
      - ./anime_tracker.session.sql:/tmp/database/anime_tracker.session.sql
    command: mysqld --init-file="/tmp/database/anime_tracker.session.sql"
