services:
  # A Docker web service
  - type: web
    name: anime_tracker_app
    runtime: docker
    repo: https://github.com/icep0ps/anime-tracker # optional
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
        
  - type: pserv
    name: mysql
    plan: free
    env: docker
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
    - fromGroup: mysql
  
  envVarGroups:
  - name: mysql
    envVars:
    - key: MYSQL_DATABASE
    - key: MYSQL_USER
    - key: MYSQL_PASSWORD
      generateValue: true
    - key: MYSQL_ROOT_PASSWORD
      generateValue: true