services:
  - type: web
    name: anime_tracker_app
    runtime: docker
    repo: https://github.com/icep0ps/anime-tracker
    region: frankfurt
    plan: free
    branch: main

  - type: pserv
    name: mysql
    plan: free
    env: docker
    autoDeploy: false
    envVars:
      - fromGroup: mysql

envVarGroups:
  - name: mysql
    envVars:
      - key: MYSQL_DATABASE
        fromService:
          type: web
          name: anime_tracker_app
          property: DATABASE
      - key: MYSQL_USER
        value: '%'
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
